### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

### ISSUE THREAD

**Issue by RdeWilde** [raymond-h/create-github-repo#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [create-github-repo](https://github.com/raymond-h/create-github-repo) package, v1.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getWorkingDirectory' of null

```
At /home/dewilde/.atom/packages/create-github-repo/lib/create-github-repo.coffee:81

TypeError: Cannot read property 'getWorkingDirectory' of null
  at Object.module.exports.git (/home/dewilde/.atom/packages/create-github-repo/lib/create-github-repo.coffee:81:42)
  at Object.module.exports.createRepository (/home/dewilde/.atom/packages/create-github-repo/lib/create-github-repo.coffee:38:4)
  at atom-workspace.disposables.add.atom.commands.add.create-github-repo:create-repo (/home/dewilde/.atom/packages/create-github-repo/lib/create-github-repo.coffee:21:6)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -3:03.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:03.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:43 nuclide-remote-projects:connect (atom-text-editor.editor.is-focused)
     -2:30 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -2:25.3.0 create-github-repo:create-repo (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -1:24.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:23.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:22.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:22.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:21.6.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -1:21.1.0 core:select-left (atom-text-editor.editor.is-focused)
 11x -1:16.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:15 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 create-github-repo:create-repo (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "node-resolver",
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-beautify, v0.28.8
atom-tsd, v0.9.0
atom-typescript, v5.2.3
autocomplete-modules, v1.0.0
color-picker, v2.0.9
create-github-repo, v1.1.0
express-complete, v0.2.0
hyperclick, v0.0.24
linter, v1.2.4
minimap, v4.12.1
node-debugger, v1.1.7
nuclide-click-to-symbol, v0.0.22
nuclide-code-format, v0.0.24
nuclide-diff-view, v0.0.24
nuclide-file-tree, v0.0.24
nuclide-file-watcher, v0.0.24
nuclide-flow, v0.0.24
nuclide-hack, v0.0.24
nuclide-hg-repository, v0.0.24
nuclide-installer, v0.0.24
nuclide-language-hack, v0.0.24
nuclide-quick-open, v0.0.24
nuclide-remote-projects, v0.0.24
nuclide-tabs, v0.0.18
nuclide-type-hint, v0.0.24
pigments, v0.9.2

# Dev
No dev packages
```

**Comment by raymond-h** [comment]
Should hopefully be fixed in 458589d301a94a200e50d592bcc18df4ebbba770.
